[build]
  publish = "."

[[redirects]]
  from = "https://a1customspa.netlify.app/*"
  to = "https://www.a1customspa.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
